let libros=
[     
 {
            titulo: "Harry Potter y la piedra filosofal",
            autor: "J.K. Rowling",
            genero: "Fantasía",
            idioma: "Español",
            precio: 20.99,
            formato: "Tapa blanda",
            isbn: "9788478884450",
            descripcion: "La historia del niño que sobrevivió y su viaje en el mundo de la magia.",
            estado: "Nuevo",
            ubicacion: "Librería Mágica",
            fecha_publicacion: "26 de junio de 1997",
            editorial: "Salamandra",
            paginas: 256,
            dimensiones: [13, 2, 20], // ancho x profundidad x altura
            peso: 350 // gramos
        },
        {
            titulo: "El Señor de los Anillos",
            autor: "J.R.R. Tolkien",
            genero: "Fantasía",
            idioma: "Español",
            precio: 25.99,
            formato: "Tapa dura",
            isbn: "9788435017941",
            descripcion: "La historia de la búsqueda del Anillo Único.",
            estado: "Nuevo",
            ubicacion: "Librería Mágica",
            fecha_publicacion: "29 de julio de 1954",
            editorial: "Minotauro",
            paginas: 432,
            dimensiones: [15, 3, 24], // ancho x profundidad x altura
            peso: 500 // gramos
        },
        {
            titulo: "El Hobbit",
            autor: "J.R.R. Tolkien",
            genero: "Fantasía",
            idioma: "Español",
            precio: 18.99,
            formato: "Tapa blanda",
            isbn: "9788435017958",
            descripcion: "La historia de Bilbo Bolsón y su viaje con los enanos.",
            estado: "Nuevo",
            ubicacion: "Librería Mágica",
            fecha_publicacion: "21 de septiembre de 1937",
            editorial: "Minotauro",
            paginas: 320,
            dimensiones: [13, 2, 20], // ancho x profundidad x altura
            peso: 300 // gramos
        },
        {
            titulo: "Cien años de soledad",
            autor: "Gabriel García Márquez",
            genero: "Novela",
            idioma: "Español",
            precio: 22.99,
            formato: "Tapa dura",
            isbn: "9788420467374",
            descripcion: "La historia de la familia Buendía y su destino.",
            estado: "Nuevo",
            ubicacion: "Librería Mágica",
            fecha_publicacion: "5 de mayo de 1967",
            editorial: "Debolsillo",
            paginas: 416,
            dimensiones: [14, 3, 22], // ancho x profundidad x altura
            peso: 450 // gramos
        },
        {
            titulo: "El Alquimista",
            autor: "Paulo Coelho",
            genero: "Ficción",
            idioma: "Español",
            precio: 15.99,
            formato: "Tapa blanda",
            isbn: "9788478884450",
            descripcion: "La historia de un joven pastor y su búsqueda de sueños.",
            estado: "Nuevo",
            ubicacion: "Librería Mágica",
            fecha_publicacion: "12 de septiembre de 1988",
            editorial: "Planeta",
            paginas: 224,
            dimensiones: [12, 2, 18], // ancho x profundidad x altura
            peso: 250 // gramos
        },
        {
            titulo: "La Sombra del Viento",
            autor: "Carlos Ruiz Zafón",
            genero: "Novela",
            idioma: "Español",
            precio: 24.99,
            formato: "Tapa dura",
            isbn: "9788408054447",
            descripcion: "La historia de un joven que encuentra un libro misterioso.",
            estado: "Nuevo",
            ubicacion: "Librería Mágica",
            fecha_publicacion: "19 de abril de 2001",
            editorial: "Planeta",
            paginas: 416,
            dimensiones: [15, 3, 24], // ancho x profundidad x altura
            peso: 500 // gramos
        },
        {
            titulo: "El Principito",
            autor: "Antoine de Saint-Exupéry",
            genero: "Ficción",
            idioma: "Español",
            precio: 12.99,
            formato: "Tapa blanda",
            isbn: "9788432040111",
            descripcion: "La historia de un príncipe que viaja por el espacio.",
            estado: "Nuevo",
            ubicacion: "Librería Mágica",
            fecha_publicacion: "6 de abril de 1943",
            editorial: "Salamandra",
            paginas: 96,
            dimensiones: [10, 1, 15], // ancho x profundidad x altura
            peso: 150 // gramos
        },
        {
            titulo: "El Amor en los Tiempos del Cólera",
            autor: "Gabriel García Márquez",
            genero: "Novela",
            idioma: "Español",
            precio: 25.99,
            formato: "Tapa dura",
            isbn: "9788420467381",
            descripcion: "La historia de un amor que dura toda una vida.",
            estado: "Nuevo",
            ubicacion: "Librería Mágica",
            fecha_publicacion: "15 de abril de 1985",
            editorial: "Debolsillo",
            paginas: 464,
            dimensiones: [15, 3, 24], // ancho x profundidad x altura
            peso: 550 // gramos
        },
        {
            titulo: "Cronicas de la Torre",
            autor: "Laura Gallego",
            genero: "Fantasía",
            idioma: "Español",
            precio: 19.99,
            formato: "Tapa blanda",
            isbn: "9788466655552",
           descripcion: "La historia de un guerrero que debe salvar su reino.",
            estado: "Nuevo",
            ubicacion: "Librería Mágica",
            fecha_publicacion: "15 de septiembre de 2006",
            editorial: "Timun Mas",
            paginas: 400,
            dimensiones: [15, 3, 24], // ancho x profundidad x altura
            peso: 500 // gramos
        },
        {
            titulo: "Alicia en el País de las Maravillas",
            autor: "Lewis Carroll",
            genero: "Ficción",
            idioma: "Español",
            precio: 15.99,
            formato: "Tapa dura",
            isbn: "9788420484187",
            descripcion: "La historia de una niña que cae por un conejo y descubre un mundo extraño.",
            estado: "Nuevo",
            ubicacion: "Librería Mágica",
            fecha_publicacion: "26 de noviembre de 1865",
            editorial: "Debolsillo",
            paginas: 160,
            dimensiones: [14, 3, 22], // ancho x profundidad x altura
            peso: 350 // gramos
        },
        {
            titulo: "El Gran Gatsby",
            autor: "F. Scott Fitzgerald",
            genero: "Novela",
            idioma: "Español",
            precio: 22.99,
            formato: "Tapa dura",
            isbn: "9788432240357",
            descripcion: "La historia del millonario Jay Gatsby y su vida de lujos y excesos.",
            estado: "Nuevo",
            ubicacion: "Librería Mágica",
            fecha_publicacion: "10 de abril de 1925",
            editorial: "Debolsillo",
            paginas: 160,
            dimensiones: [15, 3, 22], // ancho x profundidad x altura
            peso: 300 // gramos
        },
        {
            titulo: "Moby Dick",
            autor: "Herman Melville",
            genero: "Novela",
            idioma: "Español",
            precio: 21.99,
            formato: "Tapa blanda",
            isbn: "9788435018128",
            descripcion: "La historia de un capitán de barco y su obsesión con una ballena blanca.",
            estado: "Nuevo",
            ubicacion: "Librería Mágica",
            fecha_publicacion: "18 de octubre de 1851",
            editorial: "Debolsillo",
            paginas: 352,
            dimensiones: [13, 2, 20], // ancho x profundidad x altura
            peso: 375 // gramos
        },
        {
            titulo: "Veinte mil leguas de viaje submarino",
            autor: "Jules Verne",
            genero: "Novela",
            idioma: "Español",
            precio: 19.99,
            formato: "Tapa dura",
            isbn: "9788499084565",
            descripcion: "La historia de un viaje en un submarino a través de los mares del mundo.",
            estado: "Nuevo",
            ubicacion: "Librería Mágica",
            fecha_publicacion: "20 de marzo de 1870",
            editorial: "Alianza",
            paginas: 240,
            dimensiones: [14, 2, 22], // ancho x profundidad x altura
            peso: 400// gramos
        },
        {
            titulo: "La Isla del Tesoro",
            autor: "Robert Louis Stevenson",
            genero: "Aventuras",
            idioma: "Español",
            precio: 18.99,
            formato: "Tapa blanda",
            isbn: "9788466655522",
            descripcion: "La historia de un joven que busca un tesoro en una isla misteriosa.",
            estado: "Nuevo",
            ubicacion: "Librería Mágica",
            fecha_publicacion: "23 de noviembre de 1883",
            editorial: "Alianza",
            paginas: 240,
            dimensiones: [13, 2, 18], // ancho x profundidad x altura
            peso: 300 // gramos
        },
        {
            titulo: "Las Crónicas de Narnia: El león, la bruja y el armario",
            autor: "C.S. Lewis",
            genero: "Fantasía",
            idioma: "Español",
            precio: 19.99,
            formato: "Tapa blanda",
            isbn: "9780007115617",
            descripcion: "Cuatro niños descubren un mundo mágico detrás de un armario en una casa de campo.",
            estado: "Nuevo",
            ubicacion: "Librería Lewis",
            fecha_publicacion: "16 de octubre de 1950",
            editorial: "HarperCollins",
            paginas: 208,
            dimensiones: [13, 2, 20], 
            peso: 350 
        },
        {
            titulo: "Orgullo y prejuicio",
            autor: "Jane Austen",
            genero: "Novela romántica",
            idioma: "Español",
            precio: 16.99,
            formato: "Tapa blanda",
            isbn: "9788491040541",
            descripcion: "La compleja historia de amor entre Elizabeth Bennet y Mr. Darcy en la Inglaterra del siglo XIX.",
            estado: "Nuevo",
            ubicacion: "Librería Austen",
            fecha_publicacion: "28 de enero de 1813",
            editorial: "Alba Editorial",
            paginas: 416,
            dimensiones: [13, 2, 20], 
            peso: 430 
        },
        {
            titulo: "Los Juegos del Hambre",
            autor: "Suzanne Collins",
            genero: "Ciencia ficción, aventura",
            idioma: "Español",
            precio: 0, // Precio puede variar dependiendo de la edición
            formato: "Libro físico o digital",
            isbn: "Varía dependiendo de la edición",
            descripcion: "En el distópico país de Panem, Katniss Everdeen se ofrece como voluntaria para participar en los Juegos del Hambre en lugar de su hermana menor.",
            estado: "Nuevo",
            ubicacion: "Librerías",
            fecha_publicacion: "2008",
            editorial: "Molino",
            paginas: "Varía dependiendo de la edición",
            dimensiones: {
              ancho: "Varía",
              profundidad: "Varía",
              altura: "Varía"
            },
            peso: {
              valor: "Varía",
              unidad: "gramos o kilogramos"
            }
          },
          {
            titulo: "Los miserables",
            autor: "Victor Hugo",
            genero: "Ficción, Novela histórica",
            idioma: "Español (traducción)",
            precio: "Variable según la edición y vendedor",
            formato: "Tapa dura, tapa blanda, ebook, entre otros",
            ISBN: "Depende de la edición",
            descripcion: "La historia de Jean Valjean y su lucha por la redención en la Francia del siglo XIX.",
            estado: "Nuevo",
            ubicacion: "Disponible en librerías físicas y tiendas en línea",
            fechaDePublicacion: "Originalmente publicado en 1862",
            editorial: "Varias editoriales han publicado ediciones, como Penguin Clásicos",
            paginas: "Varía según la edición, generalmente alrededor de 1500 páginas",
            dimensiones: "Depende del formato",
            peso: "Depende del formato"
          },
          {
            titulo: "Crimen y castigo",
            autor: "Fyodor Dostoevsky",
            genero: "Ficción, Novela psicológica",
            idioma: "Español (traducción)",
            precio: "Variable según la edición y vendedor",
            formato: "Tapa dura, tapa blanda, ebook, entre otros",
            ISBN: "Depende de la edición",
            descripcion: "La historia de un estudiante llamado Raskólnikov que comete un asesinato y enfrenta las consecuencias psicológicas de sus acciones.",
            estado: "Nuevo",
            ubicacion: "Disponible en librerías físicas y tiendas en línea",
            fechaDePublicacion: "Originalmente publicado en 1866",
            editorial: "Varias editoriales han publicado ediciones, como Penguin Clásicos",
            paginas: "Varía según la edición, generalmente alrededor de 600 páginas",
            dimensiones: "Depende del formato",
            peso: "Depende del formato"
          },
          {
            titulo: "Rayuela",
            autor: "Julio Cortázar",
            genero: "Ficción, Experimental",
            idioma: "Español",
            precio: "Variable según la edición y vendedor",
            formato: "Tapa dura, tapa blanda, ebook, entre otros",
            ISBN: "Depende de la edición",
            descripcion: "Una novela que desafía las convenciones narrativas tradicionales y presenta múltiples formas de lectura.",
            estado: "Nuevo",
            ubicacion: "Disponible en librerías físicas y tiendas en línea",
            fechaDePublicacion: "Originalmente publicado en 1963",
            editorial: "Varias editoriales han publicado ediciones, como Alfaguara",
            paginas: "Varía según la edición, generalmente alrededor de 600 páginas",
            dimensiones: "Depende del formato",
            peso: "Depende del formato"
          }, 
]
let nuevoLibro = {
    titulo: "El Hijo del Hombre",
    autor: "Oliver Sacks",
    genero: "No ficción",
    idioma: "Español",
    precio: 25.99,
    formato: "Tapa dura",
    isbn: "9788420467374",
    descripcion: "La historia de un hombre que pierde la memoria y su lucha por recuperarla.",
    estado: "Nuevo",
    ubicacion: "Librería Mágica",
    fecha_publicacion: "5 de mayo de 2023",
    editorial: "Debolsillo",
    paginas: 416,
    dimensiones: [14, 3, 22], // ancho x profundidad x altura
    peso: 450 // gramos
};
libros.push(nuevoLibro);
let ultimoLibro = libros.pop();
console.log(libros);
libros.forEach((libros,index) => console.log(libros.titulo));
